version: "3.9"
services:
  http-server-1:
    build:
      context: ./express-docker-app
    environment:
      SERVICE_NAME: "HTTP-SERVER-1"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5001:3000"
      - "9001:9000"
    networks:
      vector:
        ipv4_address: 172.10.1.1

  http-server-2:
    build:
      context: ./express-docker-app
    environment:
      SERVICE_NAME: "HTTP-SERVER-2"
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5002:3000"
      - "9002:9000"
    networks:
      vector:
        ipv4_address: 172.10.1.2

  vector-aggregator:
    build:
      context: ./vector-docker-app
    ports:
      - "9000:9000"
      - "8383:8383"
    networks:
      vector:
        ipv4_address: 172.10.1.3

networks:
  vector:
    ipam:
      config:
        - subnet: 172.10.0.0/16